baseURL = ""
relativeurls = "true"
languageCode = "en-us"
theme = "ananke"
title = "Development and documentation site for FV"

MetaDataFormat = "toml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Syngas made better"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
#  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "/images/burner.jpg"
  recent_posts_number = 2
